---
- name: Get Junos Facts
  hosts: vMX-1
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  
  vars_prompt:
    - name: USERNAME
      prompt: User name
      private: no
    - name: DEVICE_PASSWORD
      prompt: Device Password
      private: yes
      
  tasks:
    - name: Get Junos Device Info
      juniper_junos_facts:
        user: "{{ USERNAME }}"
        passwd: "{{ DEVICE_PASSWORD }}"
      register: junos_facts
      
    - name: Print Junos Facts
      debug:
        msg: "{{ junos_facts }}"
